---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: filebeat_instance_centos7
    image: centos:7
    privileged: True
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:9001:9000/tcp
      - 0.0.0.0:8086:8080/tcp
      - 0.0.0.0:3001:3000/tcp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
