---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Install test dependencies (RedHat).
      package: name=which state=present
      when: ansible_os_family == 'RedHat'
    - name: Install test dependencies.
      package: name=curl state=present

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.elasticsearch
    - role: geerlingguy.logstash
      logstash_install_plugins:
        - logstash-input-beats
        - logstash-output-gelf
    - role: ansible-role-filebeat
    - role: orachide.springboot-service
      sb_app_name: simple-springboot-app
      sb_app_as_a_service: true
      sb_app_group_id: fr.runadium
      sb_app_artifact_id: simple-springboot-app
      sb_app_version: 0.0.1-SNAPSHOT
      sb_app_extension: jar
      sb_app_user: sbuser
      sb_app_user_group: sbgroup
      sb_java_package: java-1.8.0-openjdk
      sb_user_groups_definitions:
        - name: sbgroup
      sb_users_definition:
        - name: Simple Spring boot App User
          username: sbuser
          groups: [sbgroup]
      sb_local_maven_artifact_dowload: false
      # the test spring-boot application source is https://github.com/runadium/simple-springboot-app
      sb_app_artifact_file: "{{ playbook_dir}}/artifacts/simple-springboot-app-0.0.1-SNAPSHOT.jar"
      # sb_app_service_debug: true
      sb_app_config_file_template_path: "{{ playbook_dir }}/templates/simple-springboot-app-configuration.yml.j2"
      sb_app_config_file_final_name: application.yml
      sb_app_logback_file_template_path: "{{ playbook_dir }}/templates/logback.xml.j2"
      sb_app_java_opts_others: "-Djavax.net.debug=all -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6006"
      sb_app_healthcheck_urls:
        - "https://localhost:8443/actuator/health"
        - "http://localhost:8080/actuator/health"
      sb_app_healthcheck_ports:
        - 8080
        - 8443
    - role: graylog2.graylog-ansible-role
      graylog_install_elasticsearch: false
      graylog_install_nginx: false
      graylog_install_java: false
  post_tasks:
    - name: Remove Logstash useless configuration files
      file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/logstash/conf.d/30-elasticsearch-output.conf
        - /etc/logstash/conf.d/14-solr.conf
      notify: restart logstash
    - name: Source spring boot logstash configuration file
      template:
        src: "{{ playbook_dir }}/templates/{{ item }}.j2"
        dest: "/etc/logstash/conf.d/{{ item }}"
        mode: 0644
      with_items:
        - 16-springboot-filter.conf
        - 32-graylog-output.conf
      notify: restart logstash
    - name: Source filebeat configuration file
      template:
        src: "{{ playbook_dir }}/templates/filebeat.yml.j2"
        dest: /etc/filebeat/filebeat.yml
        mode: 0644
      notify: restart filebeat